---
run:
  timeout: 3m
  build-tags:
    - integration

linters:
  enable:
    - misspell
    - goimports
    - revive
    - gofmt
    - depguard
    - godot

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - depguard
    - path: dev-plugins/*
      linters:
        - depguard
