name: ðŸž Bug Report
description: File a bug/issue
body:
  - type: markdown
    attributes:
      value: |
        # Octopus AI: Bug Report
        Thanks for taking the time to fill out a bug/issue report!
        
        While the solutions engineering team will make a reasonable effort to respond to this issue, the Octopus AI extension has no Support Level Agreement (SLA).

  - type: input
    id: octopus-version
    attributes:
      label: Octopus version
      description: Please provide what version of Octopus you are currently running.
      placeholder: e.g., 2023.3.xxxx
    validations:
      required: true
  - type: input
    id: octopusai-version
    attributes:
      label: Octopus AI version
      description: The extension version is available in the Extensions > Manage Extensions screen in Chrome
      placeholder: e.g., 1.0.2
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: What actually happened?
      placeholder: Tell us what is wrong
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Octopus AI query output
      description: Copy the query output here
      placeholder: Log output
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: If there are specific steps that you took when you encountered the problem, please outline them here.
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: more-information
    attributes:
      label: More Information
      description: Anything else that can help us solve the problem, logs, links, screenshots, suspicions, add them here.
      placeholder: Tell us more
    validations:
      required: false

